DEFRA/epr-prn-common-backend

pipelines/ci_pipeline.yaml
pipelines/vars/Team-10_Willow-development.yaml
pipelines/vars/Team-11_Pondscrum-development.yaml
pipelines/vars/Team-1_Pi-development.yaml
pipelines/vars/Team-2_Wastebusters-development.yaml
pipelines/vars/Team-3_Recyclers-development.yaml
pipelines/vars/Team-4_QA-development.yaml
pipelines/vars/Team-5_Phoenix-development.yaml
pipelines/vars/Team-6_Stig-development.yaml
pipelines/vars/Team-7_Oscar-development.yaml
pipelines/vars/Team-8_Pre-TST-development.yaml
pipelines/vars/Team-9_Ops-development.yaml
pipelines/vars/preprod.yaml
pipelines/vars/prod.yaml
pipelines/vars/tst.yaml

Amend the app service name to from uppercase to lower and the option to disable OWASP Scan default to false so that this does not run unless checked.

disabled OWASP run and amended the App Service name to lowercase

---

src/EPR.PRN.Backend.Data/DataModels/ObligationCalculation.cs
src/EPR.PRN.Backend.Data/EprContext.cs
src/EPR.PRN.Backend.Data/Migrations/20240806090330_InitialObligationCalculation.Designer.cs
src/EPR.PRN.Backend.Data/Migrations/20240806090330_InitialObligationCalculation.cs

Add the ObligationCalculation table to EF migrations
[AB#422135](https://dev.azure.com/defragovuk/67a63f24-5d0d-4c35-9d23-885593eb7354/_workitems/edit/422135)

422135 Create ObligationCalculation table

---

src/EPR.Accreditation.BackEnd.sln
src/EPR.PRN.Backend.API/EPR.PRN.Backend.API.csproj
src/EPR.PRN.Backend.API/Helpers/DependencyHelper.cs
src/EPR.PRN.Backend.API/appsettings.json
src/EPR.PRN.Backend.Data.UnitTests/EPR.PRN.Backend.Data.UnitTests.csproj
src/EPR.PRN.Backend.Data.UnitTests/Repositories/ObligationCalculationRepositoryTests.cs
src/EPR.PRN.Backend.Data.UnitTests/Repositories/RecyclingTargetRepositoryTests.cs
src/EPR.PRN.Backend.Data/Interfaces/IObligationCalculationRepository.cs
src/EPR.PRN.Backend.Data/Repositories/ObligationCalculationRepository.cs
src/EPR.PRN.Backend.Obligation.UnitTests/EPR.PRN.Backend.Obligation.UnitTests.csproj
src/EPR.PRN.Backend.Obligation.UnitTests/Services/MaterialCalculationServiceTests.cs
src/EPR.PRN.Backend.Obligation.UnitTests/Services/ObligationCalculatorServiceTests.cs
src/EPR.PRN.Backend.Obligation.UnitTests/Services/PomSubmissionDataTests.cs
src/EPR.PRN.Backend.Obligation.UnitTests/Strategies/GeneralCalculationStrategyTests.cs
src/EPR.PRN.Backend.Obligation.UnitTests/Strategies/GlassCalculationStrategyTests.cs
src/EPR.PRN.Backend.Obligation.UnitTests/Strategies/MaterialCalculationStrategyResolverTests.cs
src/EPR.PRN.Backend.Obligation/Config/CommonDataApiConfig.cs
src/EPR.PRN.Backend.Obligation/DTO/PomObligtionDto.cs
src/EPR.PRN.Backend.Obligation/Interfaces/IMaterialCalculationService.cs
src/EPR.PRN.Backend.Obligation/Interfaces/IMaterialCalculationStrategy.cs
src/EPR.PRN.Backend.Obligation/Interfaces/IMaterialCalculationStrategyResolver.cs
src/EPR.PRN.Backend.Obligation/Interfaces/IObligationCalculatorService.cs
src/EPR.PRN.Backend.Obligation/Interfaces/IPomSubmissionData.cs
src/EPR.PRN.Backend.Obligation/Services/MaterialCalculationService.cs
src/EPR.PRN.Backend.Obligation/Services/ObligationCalculatorService.cs
src/EPR.PRN.Backend.Obligation/Services/PomSubmissionData.cs
src/EPR.PRN.Backend.Obligation/Strategies/GeneralCalculationStrategy.cs
src/EPR.PRN.Backend.Obligation/Strategies/GlassCalculationStrategy.cs
src/EPR.PRN.Backend.Obligation/Strategies/MaterialCalculationStrategyResolver.cs
src/EPR.PRN.Backend.sln

422134 and 422135
To Consume Data API and store Obligation calculation

(422134-422135) To Consume Data API and store Obligation calculation

---

src/EPR.PRN.Backend.Data.UnitTests/Repositories/ObligationCalculationRepositoryTests.cs
src/EPR.PRN.Backend.Data.UnitTests/Repositories/RecyclingTargetRepositoryTests.cs

Refactor and add new unit test
Add the ObligationCalculation table to EF migrations
[AB#422134](https://dev.azure.com/defragovuk/RWD-CPR-EPR4P-ADO/_workitems/edit/422134)

Refactor unit test

---

src/EPR.PRN.Backend.API.UnitTests/EPR.PRN.Backend.API.UnitTests.csproj
src/EPR.PRN.Backend.API/Dockerfile
src/EPR.PRN.Backend.API/EPR.PRN.Backend.API.csproj
src/EPR.PRN.Backend.Data.UnitTests/EPR.PRN.Backend.Data.UnitTests.csproj
src/EPR.PRN.Backend.Data/DataModels/ObligationCalculation.cs
src/EPR.PRN.Backend.Data/EPR.PRN.Backend.Data.csproj
src/EPR.PRN.Backend.Obligation.UnitTests/EPR.PRN.Backend.Obligation.UnitTests.csproj
src/EPR.PRN.Backend.Obligation.UnitTests/Services/ObligationCalculatorServiceTests.cs
src/EPR.PRN.Backend.Obligation/DTO/ObligationCalculationDto.cs
src/EPR.PRN.Backend.Obligation/DTO/PomObligtionDto.cs

Fix issues highlighted in SonarQube
[AB#426955](https://dev.azure.com/defragovuk/RWD-CPR-EPR4P-ADO/_workitems/edit/426955)

Fix issues highlighted in SonarQube

---

src/EPR.PRN.Backend.API.UnitTests/Controllers/PrnControllerTests.cs
src/EPR.PRN.Backend.API.UnitTests/Repositories/RepositoryTests.cs
src/EPR.PRN.Backend.API/Controllers/PrnController.cs
src/EPR.PRN.Backend.Data.UnitTests/Repositories/ObligationCalculationRepositoryTests.cs
src/EPR.PRN.Backend.Data.UnitTests/Repositories/RecyclingTargetRepositoryTests.cs
src/EPR.PRN.Backend.Data/EprContext.cs
src/EPR.PRN.Backend.Obligation.UnitTests/Services/ObligationCalculatorServiceTests.cs
src/EPR.PRN.Backend.Obligation/Interfaces/IObligationCalculatorService.cs
src/EPR.PRN.Backend.Obligation/Models/SubmissionCalculationRequest.cs
src/EPR.PRN.Backend.Obligation/Services/ObligationCalculatorService.cs

[AB#430893](https://dev.azure.com/defragovuk/RWD-CPR-EPR4P-ADO/_workitems/edit/426955)
This endpoint will trigger the calculation based on the values supplied by function app.

426955 - Create new calculate endpoint and unit tests

---

src/EPR.PRN.Backend.API/Controllers/PrnController.cs
src/EPR.PRN.Backend.Obligation/Models/SubmissionCalculationRequest.cs

[AB#426923](https://dev.azure.com/defragovuk/RWD-CPR-EPR4P-ADO/_workitems/edit/426923)

426923 Version all end points which have been created

---

src/EPR.PRN.Backend.Data/DataModels/ObligationCalculation.cs
src/EPR.PRN.Backend.Data/Migrations/20240924171141_AddMaterialWeight.Designer.cs
src/EPR.PRN.Backend.Data/Migrations/20240924171141_AddMaterialWeight.cs
src/EPR.PRN.Backend.Data/Scripts/migrations.sql
src/EPR.PRN.Backend.Obligation.UnitTests/Strategies/GeneralCalculationStrategyTests.cs
src/EPR.PRN.Backend.Obligation/Strategies/GeneralCalculationStrategy.cs
src/EPR.PRN.Backend.Obligation/Strategies/GlassCalculationStrategy.cs

[AB#430893](https://dev.azure.com/defragovuk/RWD-CPR-EPR4P-ADO/_workitems/edit/444768)

Amend PRN Backend to Save Material Weight

---

src/EPR.PRN.Backend.API/Controllers/PrnController.cs
src/EPR.PRN.Backend.Data/DataModels/Materials.cs
src/EPR.PRN.Backend.Data/Repositories/MaterialRepository.cs
src/EPR.PRN.Backend.Obligation/Interfaces/IObligationCalculatorService.cs
src/EPR.PRN.Backend.Obligation/Services/MaterialService.cs
src/EPR.PRN.Backend.Obligation/Services/ObligationCalculatorService.cs

Resolve issues with SonarQube
Not related to a user story

fix Sonarqube issues

---

src/EPR.PRN.Backend.API.UnitTests/Controllers/PrnControllerTests.cs
src/EPR.PRN.Backend.API/Controllers/PrnController.cs
src/EPR.PRN.Backend.Data.UnitTests/EPR.PRN.Backend.Data.UnitTests.csproj
src/EPR.PRN.Backend.Data.UnitTests/Repositories/PrnRepositoryTests.cs
src/EPR.PRN.Backend.Data/DTO/EprnResultsDto.cs
src/EPR.PRN.Backend.Data/DTO/EprnTonnageResultsDto.cs
src/EPR.PRN.Backend.Data/Interfaces/IPrnRepository.cs
src/EPR.PRN.Backend.Data/Repositories/PrnRepository.cs
src/EPR.PRN.Backend.Obligation.UnitTests/Services/ObligationCalculatorServiceTests.cs
src/EPR.PRN.Backend.Obligation/Constants/ObligationConstants.cs
src/EPR.PRN.Backend.Obligation/DTO/ObligationCalculationResult.cs
src/EPR.PRN.Backend.Obligation/Interfaces/IObligationCalculatorService.cs
src/EPR.PRN.Backend.Obligation/Services/ObligationCalculatorService.cs

[AB#430893](https://dev.azure.com/defragovuk/RWD-CPR-EPR4P-ADO/_workitems/edit/449093)

Feature - Add awaiting acceptance count

---

src/EPR.PRN.Backend.API.UnitTests/Controllers/PrnControllerTests.cs
src/EPR.PRN.Backend.API/Controllers/PrnController.cs

Remove Not Found error because returning zero rows is valid

Remove Not Found error getting all PRNs for organisation

---

src/EPR.PRN.Backend.Data.UnitTests/Repositories/ObligationCalculationRepositoryTests.cs
src/EPR.PRN.Backend.Data/DataModels/ObligationCalculation.cs
src/EPR.PRN.Backend.Data/Migrations/20241120151024_RenameMaterialNameToTonnage.Designer.cs
src/EPR.PRN.Backend.Data/Migrations/20241120151024_RenameMaterialNameToTonnage.cs
src/EPR.PRN.Backend.Data/Repositories/ObligationCalculationRepository.cs
src/EPR.PRN.Backend.Data/Scripts/migrations.sql
src/EPR.PRN.Backend.Obligation.UnitTests/Strategies/GeneralCalculationStrategyTests.cs
src/EPR.PRN.Backend.Obligation/DTO/ObligationData.cs
src/EPR.PRN.Backend.Obligation/Services/ObligationCalculatorService.cs
src/EPR.PRN.Backend.Obligation/Strategies/GeneralCalculationStrategy.cs
src/EPR.PRN.Backend.Obligation/Strategies/GlassCalculationStrategy.cs

[AB#469021](https://dev.azure.com/defragovuk/RWD-CPR-EPR4P-ADO/_workitems/edit/469021)

Update MaterialName to Tonnage

---

src/EPR.PRN.Backend.API.UnitTests/Controllers/PrnControllerTests.cs
src/EPR.PRN.Backend.API.UnitTests/EPR.PRN.Backend.API.UnitTests.csproj
src/EPR.PRN.Backend.API.UnitTests/Repositories/RepositoryTests.cs
src/EPR.PRN.Backend.API.UnitTests/Repositories/RepositoryTestsInMemory.cs
src/EPR.PRN.Backend.API.UnitTests/Services/PrnServiceTests.cs
src/EPR.PRN.Backend.API/Controllers/PrnController.cs
src/EPR.PRN.Backend.API/EPR.PRN.Backend.API.csproj
src/EPR.PRN.Backend.API/Repositories/Repository.cs
src/EPR.PRN.Backend.API/Services/PrnService.cs
src/EPR.PRN.Backend.API/appsettings.json
src/EPR.PRN.Backend.Data.UnitTests/Repositories/ObligationCalculationRepositoryTests.cs
src/EPR.PRN.Backend.Data/DataModels/ObligationCalculation.cs
src/EPR.PRN.Backend.Data/Migrations/20241120151024_RenameMaterialNameToTonnage.Designer.cs
src/EPR.PRN.Backend.Data/Migrations/20241120151024_RenameMaterialNameToTonnage.cs
src/EPR.PRN.Backend.Data/Repositories/ObligationCalculationRepository.cs
src/EPR.PRN.Backend.Data/Scripts/migrations.sql
src/EPR.PRN.Backend.Obligation.UnitTests/Strategies/GeneralCalculationStrategyTests.cs
src/EPR.PRN.Backend.Obligation/DTO/ObligationData.cs
src/EPR.PRN.Backend.Obligation/Services/ObligationCalculatorService.cs
src/EPR.PRN.Backend.Obligation/Strategies/GeneralCalculationStrategy.cs
src/EPR.PRN.Backend.Obligation/Strategies/GlassCalculationStrategy.cs

PRN-1 / PRN-2 Consolidated changes for sprint 10

PRN - sprint 10 merge to main 

---

src/EPR.PRN.Backend.API.UnitTests/Validators/SavePrnDetailsRequestValidatorTests.cs

uncommented commented out tests

466250: re-enabled related unit tests

---

src/EPR.PRN.Backend.API.UnitTests/Controllers/PrnControllerTests.cs
src/EPR.PRN.Backend.API.UnitTests/Services/PrnServiceTests.cs
src/EPR.PRN.Backend.API/Controllers/PrnController.cs
src/EPR.PRN.Backend.API/EPR.PRN.Backend.API.csproj
src/EPR.PRN.Backend.API/Helpers/DateTimeModelBinderProvider.cs
src/EPR.PRN.Backend.API/Program.cs
src/EPR.PRN.Backend.API/Repositories/Repository.cs
src/EPR.PRN.Backend.API/Services/PrnService.cs
src/EPR.PRN.Backend.API/Startup.cs
src/EPR.PRN.Backend.API/appsettings.Development.json
src/EPR.PRN.Backend.Data/EprContext.cs
src/EPR.PRN.Backend.Data/Repositories/ObligationCalculationRepository.cs
src/EPR.PRN.Backend.Obligation/Helpers/DateHelper.cs
src/EPR.PRN.Backend.Obligation/Services/ObligationCalculatorService.cs
src/EPR.PRN.Backend.Obligation/Strategies/GeneralCalculationStrategy.cs

Reverts DEFRA/epr-prn-common-backend#149

Revert "Bugfix/486135 fix sonar qube issues"

---

src/EPR.PRN.Backend.API.UnitTests/Repositories/RepositoryTests.cs
src/EPR.PRN.Backend.API.UnitTests/Services/PrnServiceTests.cs
src/EPR.PRN.Backend.API/Repositories/Repository.cs
src/EPR.PRN.Backend.Data/DataModels/EPRN.cs
src/EPR.PRN.Backend.Data/EprContext.cs
src/EPR.PRN.Backend.Data/Migrations/20250121153034_PrnStatusHistoryForeignKeyToPrn.Designer.cs
src/EPR.PRN.Backend.Data/Migrations/20250121153034_PrnStatusHistoryForeignKeyToPrn.cs
src/EPR.PRN.Backend.Data/Scripts/migrations.sql

* Create foreign key PrnStatusHistory to Prn
* Generate MSSQL Server scripts
---------

Create relationship Prn and PrnStatusHistory (#162)

---

src/EPR.PRN.Backend.API.UnitTests/Repositories/RepositoryTestsInMemory.cs
src/EPR.PRN.Backend.API/Repositories/Repository.cs

Adding changes done on main as part of release 8 into 8.1

syncing release 8 changes into 81

---

pipelines/vars/prod.yaml

Update prod.yaml to fix var file

Update prod.yaml to fix var file

---

src/EPR.PRN.Backend.API/Helpers/DateTimeModelBinderProvider.cs

Part of the fix to batch update Prn statuses, refer to bug https://dev.azure.com/defragovuk/RWD-CPR-EPR4P-ADO/_workitems/edit/519664

Allow controllers to accept datetimes with milliseconds

---

src/EPR.PRN.Backend.Obligation.UnitTests/Services/MaterialCalculationServiceTests.cs
src/EPR.PRN.Backend.Obligation/Services/MaterialCalculationService.cs

https://dev.azure.com/defragovuk/RWD-CPR-EPR4P-ADO/_workitems/edit/546616

546616 - Change to rounding within the glass calculation

---

src/EPR.PRN.Backend.API.UnitTests/Controllers/RegistrationMaterialControllerTests.cs
src/EPR.PRN.Backend.API/Dto/Regulator/RegistrationMaterialWasteLicencesDto.cs
src/EPR.PRN.Backend.API/Profiles/RegistrationMaterialProfile.cs

Adding necessary mapping changes

Adding new property to RegistrationMaterialWasteLicencesDto

---

src/EPR.PRN.Backend.Data/Scripts/migrations.sql

Rebuild migrations sql file, for devs previous pr, adds the Public.RegistrationTaskStatus table.

Build updated migrations.sql file.

---

src/EPR.PRN.Backend.API.UnitTests/Services/Accreditations/AccreditationFileUploadServiceTests.cs
src/EPR.PRN.Backend.Data/Repositories/Accreditations/AccreditationFileUploadRepository.cs

- Implemented changes to save submission id  into AccreditationFileUpload table
- Added unit tests

544788: EX - Accreditation - Apply - Sampling and Inspection Plan - Submit Sampling and Inspection Plan

---

src/EPR.PRN.Backend.Obligation.UnitTests/Services/ObligationCalculatorServiceTests.cs
src/EPR.PRN.Backend.Obligation/Services/ObligationCalculatorService.cs

[611451](https://dev.azure.com/defragovuk/RWD-CPR-EPR4P-ADO/_workitems/edit/611451)
**BEFORE FIX:**
**AFTER FIX:**

Adjusted RemainingGlass TonnageOutstanding using surplus GlassRemelt PRNs

---

src/EPR.PRN.Backend.API/Controllers/PrnController.cs
src/EPR.PRN.Backend.API/Startup.cs

* Restricted logging to capture minimum required info
* Added command timeout

Restricted logging to capture minimum required info (#361)
